In [3]:
import numpy as np

In [20]:
a = np.array([1, 2, 4])
a

array([1, 2, 4])

In [33]:
# 최소 dimension 지정
b = np.array([1, 2, 3, 4, 5], ndmin=2)
b

array([[1, 2, 3, 4, 5]])

In [27]:
c = np.array([1, 2, 3], dtype=float)
c

array([1., 2., 3.])

In [28]:
print(a)
a.shape

[1 2 4]


(3,)

In [34]:
print(b)
b.shape

[[1 2 3 4 5]]


(1, 5)

In [30]:
d = np.array([ [1, 2], [3, 4] ])
print(d)
d.shape

[[1 2]
 [3 4]]


(2, 2)

In [31]:
# 비표준
e = np.array([ [1, 2], [3] ])
print(e)
e.shape

[list([1, 2]) list([3])]


C:\Users\fabi8\AppData\Local\Temp/ipykernel_6948/3514142920.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  e = np.array([ [1, 2], [3] ])


(2,)

In [37]:
# 범위
print(np.arange(4))
print(np.arange(3, 9, 2))
# zeros, ones 기본 타입 float
print(np.zeros(4))
print(np.ones(4))

[0 1 2 3]
[3 5 7]
[0. 0. 0. 0.]
[1. 1. 1. 1.]


In [38]:
# identity matrix 단위 행렬
print(np.eye(3))
print(np.eye(3, 4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [40]:
# 등 간격 - 마지막 인자는 element 갯수
print(np.linspace(10, 20, 5))
print(np.linspace(2, 6, 3))

[10.  12.5 15.  17.5 20. ]
[2. 4. 6.]


In [44]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [64]:
print(b[0])
print(b[2, 1])
print(b[:, 1])
print(b.shape) # np.shape(b)
print(b.ndim) # np.ndim(b)
print(b.size) # np.size(b)
print(b.transpose()) # np.transpose(b)

# 깊은 복사 실행 - transpose 호출해도 원래 array는 그대로
c = b.copy() #np.copy(b)
print(c)
print(c.ravel()) # 1D array로
print(c.reshape(6)) #로 1D array 전환 가능
print(c) # c array는 그대로!!

[0 1]
5
[1 3 5]
(3, 2)
2
6
[[0 2 4]
 [1 3 5]]
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [67]:
a = np.array([[1, 2],
              [3, 4] ])
b = np.array([[11, 12],
              [13, 14]])
print(a + b)
print(a * b)
print(np.dot(a, b))
print(np.inner(a, b))
# (1, 2) 내적 (11, 12) , (1, 2) 내적 (13, 14)
# (3, 4) 내적 (11, 12) , (3, 4) 내적 (13, 14)

[[12 14]
 [16 18]]
[[11 24]
 [39 56]]
[[37 40]
 [85 92]]
[[35 41]
 [81 95]]


In [68]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
print(np.around(a))
print(np.ceil(a))
print(np.floor(a))

[-2.  2. -0.  1. 10.]
[-1.  2. -0.  1. 10.]
[-2.  1. -1.  0. 10.]


In [69]:
a = np.array([1.0, 5.55, 123, 0.567, 25.532])
print(np.around(a))
print(np.around(a, decimals=1))
print(np.around(a, decimals=-1))

[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [72]:
a = np.array([[3,7,5],
              [8,4,3],
              [2,4,9]])
print(np.min(a))
print(np.min(a, axis=1)) # 각 row
print(np.min(a, axis=0)) # 각 col

2
[3 3 2]
[2 4 3]


In [74]:
a = np.array([ [ [3,7], [5, 2] ],
               [ [8,4], [3, 9] ],
               [ [2,4], [9, 7] ] ])
print(np.min(a))
print(np.min(a, axis=2))
print(np.min(a, axis=1))
print(np.min(a, axis=0))

2
[[3 2]
 [4 3]
 [2 7]]
[[3 2]
 [3 4]
 [2 4]]
[[2 4]
 [3 2]]


In [75]:
a = np.array([1,2,3,4])
print(np.average(a))
print(np.std(a))
print(np.var(a))

2.5
1.118033988749895
1.25


In [103]:
print(np.random.rand(3, 3))
print(np.random.randint(0, 9, (2, 4)))
import random
random.randint(0, 9) # random의 randint는 마지막수 포함

[[0.87088307 0.60685278 0.53334946]
 [0.32908663 0.44271508 0.82678858]
 [0.24963618 0.97444772 0.12567026]]
[[8 0 2 4]
 [7 6 3 5]]


9

In [106]:
a = np.array([ [1, 2],
               [3, 4] ])
b = np.array([ [-4],
               [1]])
print(np.linalg.inv(a))
print(np.linalg.solve(a, b)) # ax = b 만족하는 x 구함
print(np.linalg.det(a))
print(np.linalg.eig(a)) # eigen value와 vector tuple 반환

[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 9. ]
 [-6.5]]
-2.0000000000000004
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
